FROM node:20.12.2-alpine as build

WORKDIR /usr/app
COPY ./package.json .
COPY ./package-lock.json . 
RUN npm i
COPY . .
RUN npm run build

FROM nginx:1.24.0-alpine
COPY --from=build /usr/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
