FROM python:3.11.9

ENV DATABASE_URL=postgresql://postgres:Pruebas12345@postgres-test:5432/medical_directory
ENV CLOUDINARY_URL=cloudinary://285242777984949:bklXZHccgFu5010Cn-optdfMEhg@drlvyvjzi

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./src /app/src

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]